// Generates one real page per app (/bereal/, /retro/, ...) from index.html,
// plus sitemap.xml. index.html is the only source: edit it, then run
//
//   node build.mjs
//
// Each sub-page keeps just the home panel and its own panel (the others are
// fetched from / when tapped), and carries its own title, description,
// canonical and structured data so search engines see distinct pages.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const SITE = "https://javi.fyi";
const today = new Date().toISOString().slice(0, 10);
const src = readFileSync("index.html", "utf8");

// panels hold no nested <div>, so each one runs to its first </div>
const PANEL_RE = /<div class="panel(?: is-active)?" data-panel="([^"]+)"[^>]*>[\s\S]*?<\/div>/g;
const panels = [...src.matchAll(PANEL_RE)].map((m) => {
  const html = m[0];
  if (/<div/.test(html.slice(4))) throw new Error(`nested <div> inside panel ${m[1]}`);
  const attr = (n) => {
    const a = html.match(new RegExp(`\\s${n}="([^"]*)"`));
    return a ? a[1].replace(/&quot;/g, '"').replace(/&amp;/g, "&") : null;
  };
  return { name: m[1], html, path: attr("data-path"), title: attr("data-title"), description: attr("data-description") };
});
const byName = Object.fromEntries(panels.map((p) => [p.name, p]));
const pages = panels.filter((p) => p.path && p.name !== "default");

const esc = (t) => t.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
const setTag = (html, re, value) => {
  if (!re.test(html)) throw new Error(`tag not found: ${re}`);
  return html.replace(re, value);
};

for (const page of pages) {
  const url = SITE + page.path;
  let html = src;

  // only home + this app + the wordless camera panel stay in the document
  html = html.replace(PANEL_RE, (m, name) => {
    if (name === "default") return m.replace(' is-active"', '"').replace(/<h1>(.*?)<\/h1>/, "<h2>$1</h2>");
    if (name === page.name) return m.replace('class="panel"', 'class="panel is-active"').replace(/<h2>(.*?)<\/h2>/, "<h1>$1</h1>");
    if (name === "camera") return m;
    return "";
  }).replace(/\n(?:[ \t]*\n){2,}/g, "\n\n");

  html = setTag(html, /<title>[^<]*<\/title>/, `<title>${esc(page.title)}</title>`);
  html = setTag(html, /<meta name="description" content="[^"]*">/, `<meta name="description" content="${esc(page.description)}">`);
  html = setTag(html, /<link rel="canonical" href="[^"]*">/, `<link rel="canonical" href="${url}">`);
  html = setTag(html, /<meta property="og:url" content="[^"]*">/, `<meta property="og:url" content="${url}">`);
  html = setTag(html, /<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${esc(page.title)}">`);
  html = setTag(html, /<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${esc(page.description)}">`);

  // structured data: this page is a WebPage about the same Person
  html = html.replace(/(<script type="application\/ld\+json">)([\s\S]*?)(<\/script>)/, (_, a, json, b) => {
    const data = JSON.parse(json);
    const person = data["@graph"].find((n) => n["@type"] === "Person");
    data["@graph"] = [
      {
        "@type": "WebPage",
        "@id": `${url}#page`,
        url,
        name: page.title,
        description: page.description,
        inLanguage: "en",
        dateModified: today,
        isPartOf: { "@type": "WebSite", "@id": `${SITE}/#site`, url: `${SITE}/`, name: "Javier Iturbe" },
        about: { "@id": person["@id"] },
      },
      person,
    ];
    const indented = JSON.stringify(data, null, 2).split("\n").map((l) => "  " + l).join("\n");
    return `${a}\n${indented}\n  ${b}`;
  });

  html = html.replace("<!DOCTYPE html>", `<!DOCTYPE html>\n<!-- generated by build.mjs from index.html — edit the source, not this file -->`);

  const dir = page.path.replace(/^\/|\/$/g, "");
  mkdirSync(dir, { recursive: true });
  writeFileSync(`${dir}/index.html`, html);
  console.log(`${page.path.padEnd(16)} ${page.title}`);
}

const urls = [byName.default, ...pages].map((p) => `  <url><loc>${SITE}${p.path}</loc><lastmod>${today}</lastmod></url>`);
writeFileSync("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join("\n")}\n</urlset>\n`);
console.log(`sitemap.xml      ${urls.length} urls`);
